"""External API Gateway — proxies authenticated 3rd-party requests to internal endpoints.

Route: ANY /api/ext/{path:path}

Auth: Bearer JWT with role="external_api" (generated by rotate-key endpoint).
Proxy: httpx self-proxy to http://127.0.0.1:{port}/api/{path} using a short-lived internal admin JWT.
"""
import hmac
import json
import logging
import re
from datetime import datetime, timedelta, timezone

import httpx
import jwt
from fastapi import APIRouter, Request
from fastapi.responses import Response

from ..config import settings
from ..services.api_catalog import ENDPOINT_CATALOG

logger = logging.getLogger(__name__)

router = APIRouter(tags=["ext-api-gateway"])


# ── Helpers ───────────────────────────────────────────────────────────────────

def _extract_bearer(request: Request) -> str | None:
    auth = request.headers.get("Authorization", "")
    if auth.startswith("Bearer "):
        return auth[7:].strip()
    return None


_GATEWAY_ROLES = {"external_api", "api_client"}


def _decode_external_jwt(token: str) -> dict | None:
    """Decode and validate an external API JWT.

    Accepted roles:
      - 'external_api': legacy static key issued by rotate-key endpoint
      - 'api_client':   service-account JWT issued by /api/auth/service-token
    """
    try:
        payload = jwt.decode(token, settings.jwt_secret, algorithms=["HS256"])
        if payload.get("role") not in _GATEWAY_ROLES:
            return None
        return payload
    except jwt.ExpiredSignatureError:
        return None
    except jwt.InvalidTokenError:
        return None


def _make_internal_admin_jwt() -> str | None:
    """Generate a short-lived (5 min) admin JWT for internal proxy calls."""
    from ..auth.user_database import UserSessionLocal
    from ..auth.models import User as UserModel
    db = UserSessionLocal()
    try:
        admin = db.query(UserModel).filter(
            UserModel.role == "admin",
            UserModel.is_active == True,  # noqa: E712
        ).first()
        if not admin:
            return None
        expires = datetime.now(timezone.utc) + timedelta(minutes=5)
        payload = {
            "sub":   str(admin.id),
            "email": admin.email,
            "role":  "admin",
            "exp":   expires,
        }
        return jwt.encode(payload, settings.jwt_secret, algorithm="HS256")
    finally:
        db.close()


def _path_matches(incoming: str, catalog_path: str) -> bool:
    """Check if incoming path (e.g. /api/controls/5/allow) matches a catalog pattern."""
    # Split on {placeholder} tokens, escape literal parts, rejoin with wildcard
    parts = re.split(r"\{[^}]+\}", catalog_path)
    pattern = "[^/]+".join(re.escape(p) for p in parts)
    return bool(re.fullmatch(pattern, incoming))


# ── Gateway route ─────────────────────────────────────────────────────────────

@router.api_route(
    "/api/ext/{path:path}",
    methods=["GET", "POST", "PUT", "DELETE", "PATCH"],
)
async def gateway(request: Request, path: str) -> Response:
    # 1. Extract and validate external API bearer token
    token = _extract_bearer(request)
    if not token:
        return Response(
            content=json.dumps({"detail": "Missing Authorization header"}),
            status_code=401,
            media_type="application/json",
        )

    payload = _decode_external_jwt(token)
    if not payload:
        return Response(
            content=json.dumps({"detail": "Invalid or expired API key"}),
            status_code=401,
            media_type="application/json",
        )

    # 2. Load DB config and check active flag
    from ..database import SessionLocal
    from ..models.external_api import ExternalApiConfig

    db = SessionLocal()
    try:
        cfg = db.get(ExternalApiConfig, 1)
    finally:
        db.close()

    if cfg is None:
        return Response(
            content=json.dumps({"detail": "External API not configured"}),
            status_code=404,
            media_type="application/json",
        )
    if not cfg.active:
        return Response(
            content=json.dumps({"detail": "External API is not active"}),
            status_code=403,
            media_type="application/json",
        )

    # api_client JWTs are short-lived user tokens validated by JWT signature above;
    # external_api tokens are static keys stored in ExternalApiConfig and must match.
    if payload.get("role") == "external_api":
        if not hmac.compare_digest(cfg.api_key or "", token):
            return Response(
                content=json.dumps({"detail": "Invalid API key"}),
                status_code=403,
                media_type="application/json",
            )

    # 3. Reconstruct full internal path
    internal_path = f"/api/{path}"
    allowed_endpoints: list[dict] = json.loads(cfg.allowed_endpoints or "[]")

    # Build a lookup: endpoint_id → mode
    allowed_map: dict[str, str] = {e["id"]: e["mode"] for e in allowed_endpoints}

    # 4. Match internal path against allowed endpoint patterns
    matched_ep = None
    matched_mode = None
    for ep in ENDPOINT_CATALOG:
        if ep["id"] not in allowed_map:
            continue
        if _path_matches(internal_path, ep["path"]):
            matched_ep = ep
            matched_mode = allowed_map[ep["id"]]
            break

    if matched_ep is None:
        return Response(
            content=json.dumps({"detail": "Endpoint not allowed"}),
            status_code=403,
            media_type="application/json",
        )

    # 5. Mode check: monitor mode only allows GET
    if matched_mode == "monitor" and request.method.upper() != "GET":
        return Response(
            content=json.dumps({"detail": "Endpoint is in monitor mode — only GET allowed"}),
            status_code=403,
            media_type="application/json",
        )

    # 6. Generate short-lived internal admin JWT
    internal_token = _make_internal_admin_jwt()
    if not internal_token:
        return Response(
            content=json.dumps({"detail": "Internal error: no admin user available"}),
            status_code=500,
            media_type="application/json",
        )

    # 7. Forward request via httpx (preserve query string + body)
    base_url = f"http://127.0.0.1:{settings.app_port}"
    query = str(request.url.query)
    target_url = f"{base_url}{internal_path}"
    if query:
        target_url = f"{target_url}?{query}"

    body = await request.body()

    try:
        async with httpx.AsyncClient(timeout=15.0) as client:
            resp = await client.request(
                method=request.method,
                url=target_url,
                content=body if body else None,
                headers={
                    "Authorization":  f"Bearer {internal_token}",
                    "Content-Type":   request.headers.get("Content-Type", "application/json"),
                    "Accept":         request.headers.get("Accept", "application/json"),
                },
            )
    except httpx.RequestError as e:
        logger.warning(f"Gateway proxy error for {internal_path}: {e}")
        return Response(
            content=json.dumps({"detail": f"Upstream error: {e}"}),
            status_code=502,
            media_type="application/json",
        )

    # 8. Pass through response
    content_type = resp.headers.get("content-type", "application/json")
    return Response(
        content=resp.content,
        status_code=resp.status_code,
        media_type=content_type,
    )
