#!/usr/bin/env node
/**
 * setup-env.js
 *
 * Detects the machine's LAN IP using Node's built-in `os` module and writes
 * mobile/.env so that the Expo app can reach the FastAPI backend from a
 * physical device on the same Wi-Fi network.
 *
 * Runs automatically before every `npm start / android / ios / web`.
 * No external dependencies required.
 */

const os   = require('os')
const fs   = require('fs')
const path = require('path')

// ─── Find candidate LAN IPs ──────────────────────────────────────────────────
function getLanIps() {
  const results = []
  const ifaces  = os.networkInterfaces()

  for (const [name, addrs] of Object.entries(ifaces)) {
    for (const addr of addrs) {
      if (addr.family !== 'IPv4') continue
      if (addr.internal)         continue           // skip loopback 127.x
      if (addr.address.startsWith('169.254')) continue // skip link-local
      results.push({ name, address: addr.address })
    }
  }
  return results
}

// ─── Pick best IP (prefer Wi-Fi / WLAN over virtual adapters) ───────────────
function pickBestIp(candidates) {
  if (candidates.length === 0) return null

  // Prefer interfaces whose name suggests real network hardware
  const preferred = candidates.find(({ name }) =>
    /wi.?fi|wlan|wireless|en\d|eth\d|local area/i.test(name)
  )
  return preferred ?? candidates[0]
}

// ─── Write .env ──────────────────────────────────────────────────────────────
const candidates = getLanIps()
const chosen     = pickBestIp(candidates)
const envPath    = path.join(__dirname, '..', '.env')

// Preserve the ERP API key across regenerations. setup-env rewrites .env on
// every start, but the NFC scan endpoint (POST /api/nfc/scan) needs the static
// ERP X-API-Key, which the developer sets ONCE. We carry it over from the
// existing .env, or accept it via the MARINA_ERP_API_KEY env var. The value is
// never auto-detected — leave the placeholder until you paste the NUC's key.
function readPreservedErpKey() {
  if (process.env.MARINA_ERP_API_KEY) return process.env.MARINA_ERP_API_KEY
  try {
    const prev = fs.readFileSync(envPath, 'utf8')
    const m = prev.match(/^EXPO_PUBLIC_ERP_API_KEY=(.*)$/m)
    if (m && m[1].trim()) return m[1].trim()
  } catch { /* no existing .env yet */ }
  return ''
}
const erpKey  = readPreservedErpKey()
const erpLine =
  `# NFC scan auth — paste the NUC's ERP_API_KEY here (kept across restarts).\n` +
  `EXPO_PUBLIC_ERP_API_KEY=${erpKey}\n`

if (!chosen) {
  console.warn('\n[setup-env] ⚠  Could not detect a LAN IP address.')
  console.warn('[setup-env]    Make sure you are connected to Wi-Fi or Ethernet.')
  console.warn('[setup-env]    Falling back to localhost (Expo Go on a physical device will NOT work).\n')

  fs.writeFileSync(envPath,
    '# WARNING: No LAN IP detected — physical device testing will fail\n' +
    'EXPO_PUBLIC_API_URL=http://localhost:8000\n' +
    'EXPO_PUBLIC_WS_URL=ws://localhost:8000/ws\n' +
    erpLine,
    'utf8'
  )
  process.exit(0)
}

const ip      = chosen.address
const content =
  `# Auto-generated by scripts/setup-env.js — do not edit manually\n` +
  `# (except EXPO_PUBLIC_ERP_API_KEY, which is preserved across runs)\n` +
  `# Detected interface: ${chosen.name}\n` +
  `EXPO_PUBLIC_API_URL=http://${ip}:8000\n` +
  `EXPO_PUBLIC_WS_URL=ws://${ip}:8000/ws\n` +
  erpLine

fs.writeFileSync(envPath, content, 'utf8')

// ─── Console output ──────────────────────────────────────────────────────────
console.log('\n┌─────────────────────────────────────────────────┐')
console.log('│            Marina IoT — Expo setup              │')
console.log('├─────────────────────────────────────────────────┤')
console.log(`│  Interface : ${chosen.name.padEnd(34)}│`)
console.log(`│  LAN IP    : ${ip.padEnd(34)}│`)
console.log(`│  API URL   : http://${ip}:8000`.padEnd(51) + '│')
console.log('├─────────────────────────────────────────────────┤')

if (candidates.length > 1) {
  console.log('│  Other detected interfaces:                     │')
  for (const c of candidates) {
    if (c.address !== ip) {
      console.log(`│    ${c.name}: ${c.address}`.padEnd(51) + '│')
    }
  }
  console.log('├─────────────────────────────────────────────────┤')
}

console.log('│  .env written ✓  Make sure phone is on the     │')
console.log('│  same Wi-Fi and backend runs with:              │')
console.log('│  uvicorn app.main:app --host 0.0.0.0 --reload  │')
console.log('└─────────────────────────────────────────────────┘\n')
