"""
Guard persistence (step 5).

These tables live in `pedestal.db` alongside the other IoT/hardware state. **The backend is
the only writer.** The worker never opens a database: it publishes over MQTT and
`app/guard/service.py` persists what arrives. The worker is the only writer of FILES under
`/var/lib/marina-guard/`, and the backend only reads those. So there is one writer for the
database and one for the files, in different processes, with no overlap — see
`docs/guard_b1_addendum_file_ownership.md`.

Four tables, and the split between the last two is deliberate:

  * `guard_config`     — desired state + the runtime-tunable thresholds. One row per camera.
  * `guard_events`     — ALARMS. What the operator sees and labels.
  * `guard_detections` — EVERY detection above the logging floor, including below-threshold
    ones. These are the missing A.5 accuracy rows and the Phase 2 training index. They are
    NOT alarms, and keeping them in their own table is what stops "we detected something
    faint" from ever being confused with "the alarm fired".
  * `guard_recordings` — one row per assembled clip, linked to its event.

`camera_id` is the pedestal id (B1 §6.4: no camera entity exists yet, one camera per
pedestal), but it is stored as its own column and referenced everywhere as `camera_id` so a
real `cameras` table can be introduced later without rewriting every query.
"""
from datetime import datetime

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)

from ..database import Base

# Guard states. Mirrors guard_worker.watchdog so the two halves cannot drift apart in
# meaning; the worker owns the transitions, the backend owns the desired state.
STATE_OFF = "OFF"
STATE_ARMING = "ARMING"
STATE_ARMED = "ARMED"
STATE_ALARM = "ALARM"
STATE_RECORDING = "RECORDING"
STATE_SUSPENDED_CPU = "SUSPENDED_CPU"
STATE_NO_DISK = "NO_DISK"
STATE_UNAVAILABLE = "UNAVAILABLE"

# Bands, mirroring app.guard.pipeline.
BAND_UNCERTAIN = "uncertain"
BAND_ALARM = "alarm"

LABEL_CORRECT = "correct"
LABEL_FALSE_ALARM = "false_alarm"


class GuardConfig(Base):
    """Desired state and runtime thresholds. One row per camera.

    Every threshold here is changeable via `PATCH /api/guard/{camera_id}/config` with no
    redeploy, because guard's accuracy is unproven and has to be tuned in production.
    `config_version` increments on every change and rides along in the MQTT command, so the
    worker can report which version it is actually running — a silent config mismatch
    between backend and worker would make tuning results meaningless.

    `desired_state` is the backend's intent, NOT what the worker is doing. The two are
    reconciled in `service.py`; the difference is how "Guard unavailable" is detected rather
    than a false ARMED being shown.
    """

    __tablename__ = "guard_config"

    camera_id = Column(Integer, primary_key=True)
    pedestal_id = Column(Integer, nullable=False, index=True)
    berth_id = Column(Integer, nullable=True)

    # OFF | ARMED | SUSPENDED_CPU. A guard suspended by the watchdog comes back SUSPENDED
    # after a restart, never silently armed — the backend holds that fact, which is why it
    # is persisted here rather than inferred from the worker.
    desired_state = Column(String, nullable=False, default=STATE_OFF)
    suspended_reason = Column(String, nullable=True)
    suspended_at = Column(DateTime, nullable=True)

    config_version = Column(Integer, nullable=False, default=1)

    # ── runtime-tunable detection settings ──
    conf_threshold = Column(Float, nullable=False, default=0.50)
    uncertain_min = Column(Float, nullable=False, default=0.20)
    fps = Column(Float, nullable=False, default=1.0)
    window_seconds = Column(Float, nullable=False, default=4.0)
    frames_required = Column(Integer, nullable=False, default=2)
    cooldown_seconds = Column(Float, nullable=False, default=60.0)
    # Detection zone, fractions of the frame. The crop is what gives usable range
    # (~25-30 m vs ~15 m), so it is tunable but never absent by default.
    zone_x1 = Column(Float, nullable=False, default=0.20)
    zone_y1 = Column(Float, nullable=False, default=0.20)
    zone_x2 = Column(Float, nullable=False, default=0.80)
    zone_y2 = Column(Float, nullable=False, default=0.80)
    visibility_min_luma = Column(Float, nullable=False, default=30.0)
    visibility_min_variance = Column(Float, nullable=False, default=15.0)

    updated_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    updated_by = Column(String, nullable=True)


class GuardEvent(Base):
    """One alarm.

    `event_uuid` is generated by the WORKER and is the idempotency key: MQTT is at-least-once
    at QoS 1, so the same alarm can arrive twice and must not become two events. The unique
    constraint is what makes the backend's persistence idempotent rather than hopeful.
    """

    __tablename__ = "guard_events"

    id = Column(Integer, primary_key=True, index=True)
    event_uuid = Column(String, nullable=False, unique=True, index=True)
    camera_id = Column(Integer, nullable=False, index=True)
    pedestal_id = Column(Integer, nullable=True)
    berth_id = Column(Integer, nullable=True)

    # Both stamps are stored, per the spec. UTC is the truth; local is what the operator
    # recognises when reading the list at the pier, and computing it later would need the
    # marina timezone at read time rather than at the moment it happened.
    detected_at_utc = Column(DateTime, nullable=False, index=True)
    detected_at_local = Column(String, nullable=True)

    confidence = Column(Float, nullable=False, default=0.0)
    px_height = Column(Float, nullable=True)
    bbox = Column(Text, nullable=True)                 # JSON [x1,y1,x2,y2], normalised
    trigger = Column(String, nullable=True)            # e.g. "2_in_4s"
    limited_visibility = Column(Boolean, nullable=False, default=False)

    frame_path = Column(String, nullable=True)         # annotated JPEG, worker-written
    video_path = Column(String, nullable=True)
    video_skipped = Column(Boolean, nullable=False, default=False)
    video_skip_reason = Column(String, nullable=True)  # "no_disk" | "assembly_failed" | …

    # Operator labelling — the dataset from day one.
    label = Column(String, nullable=True)              # correct | false_alarm
    label_note = Column(Text, nullable=True)
    labelled_at = Column(DateTime, nullable=True)
    labelled_by = Column(String, nullable=True)

    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)

    __table_args__ = (
        Index("ix_guard_events_camera_time", "camera_id", "detected_at_utc"),
    )


class GuardDetection(Base):
    """Every detection above the logging floor, alarm or not.

    Deliberately separate from `guard_events`: an uncertain detection is not an alarm, and a
    frame with nothing in it writes NO row at all, so absence stays absence. These rows are
    the accuracy evidence the A.5 person-clip run could not produce and the Phase 2 training
    index; they cannot be reconstructed after the fact, which is why detection runs at
    `uncertain_min` rather than at the alarm threshold.

    Written in batches (the worker publishes every ~5 s) in one transaction per batch, so
    per-frame inserts never contend with the marina's session writes.
    """

    __tablename__ = "guard_detections"

    id = Column(Integer, primary_key=True, index=True)
    camera_id = Column(Integer, nullable=False, index=True)
    detected_at = Column(DateTime, nullable=False, index=True)
    confidence = Column(Float, nullable=False)
    px_height = Column(Float, nullable=True)
    bbox = Column(Text, nullable=True)
    band = Column(String, nullable=False)              # uncertain | alarm
    frame_path = Column(String, nullable=True)         # None when rate-limited away
    limited_visibility = Column(Boolean, nullable=False, default=False)
    # Set when this detection contributed to an alarm, so the training index can be filtered
    # to "what the rule actually fired on".
    event_uuid = Column(String, nullable=True, index=True)

    __table_args__ = (
        Index("ix_guard_detections_camera_time", "camera_id", "detected_at"),
    )


class GuardRecording(Base):
    """One assembled clip.

    `deleted_at` is set rather than the row being removed, so a 410 Gone can say *when* and
    *why* the video went — which is a different fact from "no such event" and is what the
    dashboard needs to render "video expired" instead of a broken link.
    """

    __tablename__ = "guard_recordings"

    id = Column(Integer, primary_key=True, index=True)
    event_uuid = Column(String, nullable=True, index=True)
    camera_id = Column(Integer, nullable=False, index=True)
    started_at = Column(DateTime, nullable=False)
    duration_s = Column(Float, nullable=True)
    file_path = Column(String, nullable=False)
    file_size = Column(Integer, nullable=True)
    confidence = Column(Float, nullable=True)

    deleted_at = Column(DateTime, nullable=True)
    delete_reason = Column(String, nullable=True)      # max_days | max_gb | missing_on_disk

    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)

    __table_args__ = (
        UniqueConstraint("file_path", name="uq_guard_recording_path"),
    )
